- productMods/templates/freemarker/body/partials/individual/propStatement-educationalTraining.ftl
- productMods/templates/freemarker/body/partials/individual/propStatement-fullName.ftl
Added a couple additional schema.org itemscope changes to some of the propStatement files. I wrapped some text in spans which shouldn't cause css formatting issues unless specifically targeted.
> minor changes for University and Person names with schema.org markup

- themes/wilma/i18n/all.properties
grants on grants on grants on grants
> Fix typo on intro_para2

- webapp/src/main/webapp/config/listViewConfig-researchAreaOf.xml
- webapp/src/main/webapp/templates/freemarker/body/partials/individual/propStatement-researchAreaOf.ftl
See https://jira.duraspace.org/browse/VIVO-1225
> hide past positions in 'research area of' list view

- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/ManageLabelsForPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/VIVODefaultAddMissingIndividualFormGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/VIVONewIndividualFormGenerator.java
Trivial fix for some missing spaces in prefix declarations for N3 parsing.
> adding missing space from prefix definitions

- api/src/main/java/edu/cornell/mannlib/semservices/service/impl/LCSHService.java
Update to the LCSH implementation for the vocabulary lookup for subject areas and research areas.
> fixing LCSH lookup

- .github/PULL_REQUEST_TEMPLATE.md
**Thank you for submitting a pull request! Title this pull request with a brief description of what the pull request fixes/improves/changes. Please describe the pull request in detail using the template below.**
* * *
**[JIRA Issue](https://jira.duraspace.org)**: https://jira.duraspace.org/browse/VIVO-1437
* https://wiki.duraspace.org/display/VIVO/2018-02-06+-+VIVO+Development+IG
Adds a pull request template. See https://github.com/blog/2111-issue-and-pull-request-templates for a little information on pull request templates.
This adds a new .github directory and the template text file.
The pull request form should be auto-populated with this form once the pull request is accepted. Only affects functionality on github.com, not the application. 
N/A
@awoods
> VIVO-1437 Add pull request template

- pom.xml
Resolves: https://jira.duraspace.org/browse/VIVO-1523
> Allow retrieval of SNAPSHOT dependencies

- README.md
- api/pom.xml
- pom.xml
pom.xml - Updated profiles - release to release-sign-artifacts, added activation, added repository to distributionManagement, updated nexus-staging-maven-plugin version to 1.6.7
Updated pom.xml - orcid-api-client version to 0.6.3
README.md - Changed to 1.10 URL
> Rel 1.10.0 rc

- paper/paper.md
:wave: this is a small collection of fixes for your JOSS submission over in https://github.com/openjournals/joss-reviews/issues/943 / cc @mconlon17
> Small fixes to JOSS paper

- README.md
Resolves: https://jira.duraspace.org/browse/VIVO-1618
Minor: Adds Travis-CI build status badge to README.md
Verify that Travis-CI badge is included near top of README.md
> Add Travis-CI Badge to README.md

- .gitignore
- webapp/src/main/webapp/WEB-INF/resources/startup_listeners.txt
Related to: https://jira.duraspace.org/browse/VIVO-1600
See: vivo-project/Vitro#87
> Update default startup_listeners.txt for ElasticSearch

- api/src/main/java/edu/cornell/mannlib/semservices/service/impl/AgrovocService.java
**[VIVO-1647](https://jira.duraspace.org/browse/VIVO-1647)**
Improves the code in AgrovocService.java to use the diamond operator in declarations.
Eight changes to declarations.  No changes to function.
Build, navigate to a profile, and add a concept to the person's research areas using the Agrovoc vocabulary.  It should work as before.
@VIVO-project/vivo-contributors @vivo-project/vivo-developers @vivo-project/vivo-committers
> [VIVO 1647] - Improve AgrovocService.java using diamond operator

- home/src/main/resources/rdf/tbox/firsttime/vitroAnnotations.n3
This pull request is part of https://github.com/vivo-project/Vitro/pull/76 .
> [VIVO-1528] annotate fields for HTML editing

- home/src/main/resources/config/example.runtime.properties
Update to allow the TPF API to be toggled via the runtime.properties.
> VIVO-1614 - Update to allow the TPF API to be toggled via the runtime.properties.

- pom.xml
Resolves: https://jira.lyrasis.org/browse/VIVO-1747
> Update puppycrawl dependency to 8.29

- README.md
**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1754)**: VIVO-1754
VIVO is mentioned in scholarly articles pretty regularly. The Readme.md should be updated to guide scholars to a proper citation. This will make it easier to track VIVO related research, too.
This PR adds the JOSS citation as text and as BibTeX.
No side effects.
Someone should try if the BibTeX works. 
If this PR is accepted this information should be included in the documentation and the http://vivoweb.org/, too.
@mconlon17
> Added citation information for JOSS paper

- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddOrganizerRoleToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddPublicationToPersonGenerator.java
Fixed whitespace/tab indentations
> My whitespace

- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddAttendeeRoleToPersonGenerator.java
Fixed whitespace/tabs indentations
> Fixed indentations

- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddClinicalRoleToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddMemberRoleToPersonGenerator.java
Removed extraneous whitespaces in AddClinicalRoleToPersonGenerator.java / AddMemberRoleToPersonGenerator.java
> Removed extraneous whitespace

- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddAttendeeRoleToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddClinicalRoleToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddEditorRoleToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddEditorshipToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddHeadOfRoleToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddMemberRoleToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddOrganizerRoleToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddPublicationToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddResearcherRoleToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddReviewerRoleToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddServiceProviderRoleToPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/GeneratorUtil.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/ManageWebpagesForIndividualGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/visualization/capabilitymap/CapabilityMapRequestHandler.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/visualization/utilities/CachingRDFServiceExecutor.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/visualization/utilities/VisualizationCaches.java
-Add-Feature
-Optimization
-Linguistic-Management
-Bug-Correction
> Tagging UQAM comments with the following tags

- webapp/src/main/webapp/templates/freemarker/edit/forms/addAssociatedConcept.ftl
[VIVO-1844](https://jira.lyrasis.org/browse/VIVO-1844)
Includes https://github.com/vivo-project/VIVO-languages/pull/65
> [VIVO-1844] replace static headings with i18n values

- api/src/main/java/edu/cornell/mannlib/vitro/webapp/visualization/utilities/VisualizationCaches.java
**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1900)**
[2nd PR](https://github.com/vivo-project/Vitro/pull/181) with description
> [VIVO-1900] i18n: added empty check for getCountry, fixing bug with spanish label (es)

- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/ManageWebpagesForIndividualGenerator.java
Related to: https://jira.lyrasis.org/browse/VIVO-1906
Minor compile-time bug fix - allows VIVO to build
> Fix bug of missing toString()

- home/src/main/resources/rdf/tbox/filegraph/catalog-v001.xml
- home/src/main/resources/rdf/tbox/filegraph/vivo.owl
**Thank you for submitting a pull request! Title this pull request with a brief description of what the pull request fixes/improves/changes. Please describe the pull request in detail using the template below.**
* * *
Adding terms for issues 760-763 in vivo-isf-ontology repo
Moving two terms adding for issues 758 and 759 in vivo-isf-ontology repo
This PR adds terms needed for the RDA/TDWG attribution standard. The terms are related to giving credit for collections management.
- Collection Process and Curation Process are now subclasses of planned process. This is in line with how this is represented in OBI and in BCO.
- Terms from BCO and OBI have been added where appropriate as subclasses of either Collection …
> adding collections process terms

- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/ManageLabelsForPersonGenerator.java
- webapp/src/main/webapp/templates/freemarker/body/individual/manageLabelsForIndividualAddForm.ftl
[Jira Issue](https://jira.lyrasis.org/browse/VIVO-1915) 
For description see main [PR](https://github.com/vivo-project/Vitro/pull/184)
> [VIVO-1915] i18n - removing language select for label management for individuals

- webapp/src/main/webapp/templates/freemarker/edit/forms/addConceptThroughObjectPropertyAutoComplete.ftl
- webapp/src/main/webapp/templates/freemarker/edit/forms/defaultAddMissingIndividualForm.ftl
https://jira.lyrasis.org/browse/VIVO-1916
> - added i18n() to hardcoded values

- api/src/main/java/edu/cornell/mannlib/vitro/webapp/visualization/utilities/VisualizationCaches.java
**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1867**
This Pr adds i18n-support for a person's domain in the capability map. For problem/bug description see Jira ticket.
The new SPARQL-Query will look for a appropriate label related to the selected language in this order:
1. label with the selected language + country (like "en-US")
2. label with the selected language (like "en")
3. label with the selected language and no matter which country (like "en-*", for example "en-CA")
4. any label no matter which langauge
With the sample data (https://raw.githubusercontent.com/vivo-project/sample-data/master/sample-data.n3) go to "/vivo/organizations" and pick something (for example englisch) and add labels for some languages.
Then move to "/vivo/vis/capabilitymap" and search for something …
> [VIVO-1867] i18n: person's domain appears in English in French capability map

- home/src/main/resources/config/example.runtime.properties
Follow-on to: https://jira.lyrasis.org/browse/VIVO-1936
Re-enables build.
> Minor checkstyle correction following: VIVO-1936

- installer/example-settings.xml
**Thank you for submitting a pull request! Title this pull request with a brief description of what the pull request fixes/improves/changes. Please describe the pull request in detail using the template below.**
* * *
**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1936)**: (please link to issue)
Follow-up on https://github.com/vivo-project/VIVO/pull/203
> follow-up on vivo-1936 - restore default values in example-settings.xml

- home/src/main/resources/config/example.applicationSetup.n3
- home/src/main/resources/rdf/tbox/filegraph/vivo.owl
- webapp/src/main/webapp/templates/freemarker/body/orcid/orcidConfirm.ftl
This will bring the sprint branch back up to speed with the main branch. We are targeting Monday to merge sprint-i18n back into main.
@awoods @wwelling @vivo-project/vivo-committers
> Merge main back into sprint-i18n in prep for big merge

- api/src/main/java/edu/cornell/mannlib/semservices/service/impl/AgrovocService.java
- api/src/main/java/edu/cornell/mannlib/semservices/service/impl/LCSHService.java
Cleaned up version of https://github.com/vivo-project/VIVO/pull/201
https://jira.lyrasis.org/browse/VIVO-1949
> [VIVO-1949] - Fix external AGROVOC and LCSH service URLs

- webapp/src/main/webapp/templates/freemarker/body/partials/individual/individual-visualizationFoafPerson.ftl
- webapp/src/main/webapp/templates/freemarker/visualization/coauthorship/coAuthorshipSparklineContent.ftl
- webapp/src/main/webapp/templates/freemarker/visualization/coauthorship/coAuthorshipStandaloneActivator.ftl
- webapp/src/main/webapp/templates/freemarker/visualization/copi/coInvestigationSparklineContent.ftl
- webapp/src/main/webapp/templates/freemarker/visualization/copi/coInvestigationStandaloneActivator.ftl
- webapp/src/main/webapp/templates/freemarker/visualization/grant/personGrantCountStandaloneActivator.ftl
- webapp/src/main/webapp/templates/freemarker/visualization/grant/personGrantSparklineContent.ftl
- webapp/src/main/webapp/templates/freemarker/visualization/personlevel/coAuthorPersonLevelD3.ftl
- webapp/src/main/webapp/templates/freemarker/visualization/personlevel/coPIPersonLevelD3.ftl
- webapp/src/main/webapp/templates/freemarker/visualization/publication/personPublicationCountStandaloneActivator.ftl
- webapp/src/main/webapp/templates/freemarker/visualization/publication/personPublicationSparklineContent.ftl
**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1950)**: https://jira.lyrasis.org/browse/VIVO-1950
Fixes an error where google visualization libraries were not loading correctly.
Should just be a return of normal function
See description on how to replicate on issue: https://jira.lyrasis.org/browse/VIVO-1950
Deploy changes, visit pages with Sparkline graphs and confirm they work.
@VIVO-project/vivo-committers @awoods
> [VIVO-1950] - Update to google chart library loads

- api/pom.xml
- home/pom.xml
- installer/home/pom.xml
- installer/pom.xml
- installer/webapp/pom.xml
- pom.xml
- webapp/pom.xml
**[https://jira.lyrasis.org/browse/VIVO-1999](https://jira.lyrasis.org/browse/VIVO-1999)**: 
Use with other three pull requests linked to JIRA issue.
Confirm that VIVO builds and runs normally.
> Update version numbers in pom.xmls

- installer/home/pom.xml
- installer/webapp/pom.xml
* Uncomment missing language dependencies
* Revert target home directory to generic name
**Thank you for submitting a pull request! Title this pull request with a brief description of what the pull request fixes/improves/changes. Please describe the pull request in detail using the template below.**
* * *
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: (please link to issue)
A brief description of what the intended result of the PR will be and/or what problem it solves.
An in-depth description of the changes made by this PR. Technical details and possible side effects. Include screenshots if appropriate.
Example:
* Changes x feature to such that y
* Added x
* Removed y
A description of what …
> Uncomment missing language dependencies (#3611)

- .github/workflows/build.yml
- home/src/main/resources/config/example.runtime.properties
- installer/home/pom.xml
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3603)**: (please link to issue)
Goes with [Vitro PR](https://github.com/vivo-project/Vitro/pull/251)
Goes with [Vitro-languages PR](https://github.com/vivo-project/Vitro-languages/pull/56)
Provides configuration example for document upload.
Adds dependency on vitro-languages-home-core
> Upload documents in Vitro|VIVO

- home/src/main/resources/config/example.runtime.properties
> Email settings example for VIVO

- webapp/src/main/webapp/templates/freemarker/body/individual/individual--foaf-person-quickview.ftl
- webapp/src/main/webapp/templates/freemarker/body/partials/individual/individual-geographicFocus.ftl
- webapp/src/main/webapp/templates/freemarker/body/partials/individual/individual-positions.ftl
- webapp/src/main/webapp/templates/freemarker/body/partials/individual/individual-researchAreas.ftl
- webapp/src/main/webapp/themes/tenderfoot/templates/body/individual/individual--foaf-person.ftl
- webapp/src/main/webapp/themes/wilma/templates/individual--foaf-person.ftl
[Companion PR VIVO-languages](https://github.com/vivo-project/VIVO-languages/pull/117)
[Companion PR Vitro-languages](https://github.com/vivo-project/Vitro-languages/pull/65)
Imported fix from French templates:
Removed capitalization from translation that is already capitalized in English and shouldn't be capitalized in French
@chenejac
> [i18n sprint ] imported fixes from fr_CA theme and individual templates

- webapp/src/main/webapp/js/homePageUtils.js
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3774](https://github.com/vivo-project/VIVO/issues/3774)
Fixing a tiny typo
> fix for a small typo in a js file

- webapp/src/main/webapp/templates/freemarker/lib/lib-home-page.ftl
- webapp/src/main/webapp/themes/nemo/templates/lib-home-page.ftl
- webapp/src/main/webapp/themes/tenderfoot/css/page-home.css
- webapp/src/main/webapp/themes/wilma/css/wilma.css
[Companion PR](https://github.com/vivo-project/VIVO-languages/pull/115)
#What does this pull request do?#
Moved translations from language specific lib-home-page templates to properties.
Redesigned research statistic on home page.
#How to test#
For themes wilma, nemo, tenderfoot:
Open home page, view list of research types
> [ i18n sprint ] Move translations from language specific lib-home-page templates to properties.

- webapp/src/main/webapp/js/visualization/entitycomparison/util.js
- webapp/src/main/webapp/templates/freemarker/visualization/entitycomparison/entityComparisonSetup.ftl
[VIVO-languages companion PR](https://github.com/vivo-project/VIVO-languages/pull/119)
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: (please link to issue)
Adds localizations for search button text and records list in publication graph
* Open /vis/publication-graph
* Verify that search text is translated
* Verify that Records X - Y of Z is translated
@hauschke 
@chenejac
> [i18n] Localizations for search button and records list in publication graph

- webapp/src/main/webapp/WEB-INF/resources/startup_listeners.txt
[Vitro PR](https://github.com/vivo-project/Vitro/pull/341)
Convert all property files into i18n model on the fly.
@vivo-project/vivo-committers
> [i18b sprint] 3760 translations loading

- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/ManageLabelsForPersonGenerator.java
- api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/ManageWebpagesForIndividualGenerator.java
- installer/home/pom.xml
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3800](https://github.com/vivo-project/VIVO/issues/3800)
[Companion PR](https://github.com/vivo-project/Vitro/pull/351)
Adding support for local customization of UI labels by using language tags. It means an institution can add in the directory <VIVO HOME>/rdf/i18n/ its own local customization of translations. Those local, institution-specific translations should be in the directory which name is aligned with language tag specification for private tags (for instance fr_CA_x_uqam or de_DE_x_tib). The idea is similar as for property files and usage of <tomcat>webapps/i18n/local directory. The institution can easily update VIVO version, and continue to use previously customized labels and vocabularies. 
- Replacing …
> [3800 i18n redesign] Supporting private tags

- webapp/src/main/webapp/css/visualization/entitycomparison/layout.css
- webapp/src/main/webapp/templates/freemarker/visualization/entitycomparison/entityComparisonSetup.ftl
- webapp/src/main/webapp/themes/tenderfoot/css/page-home.css
- webapp/src/main/webapp/themes/tenderfoot/css/tenderfoot.css
- webapp/src/main/webapp/themes/wilma/css/wilma.css
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [William's testing](https://github.com/vivo-project/VIVO/pull/3805#issuecomment-1405032435)
Fixing some layout issues reported by William at this [PR's review](https://github.com/vivo-project/VIVO/pull/3805#issuecomment-1405032435) 
Small corrections of css files
Some languages has undesired word wrapping.
The bottom horizontal line is not bottom padded as much as the other like sections.
Padding is cramped. Worse in some languages. But all have no space right of the search label.
Tag (@ mention) interested parties or, if unsure, @VIVO-project/vivo-committers @wwelling
> [i18n redesign] fixing issues with layout

- home/src/main/resources/rdf/i18n/de_DE/display/firsttime/search_individuals_vivo.n3
- home/src/main/resources/rdf/i18n/en_CA/display/firsttime/search_individuals_vivo.n3
- home/src/main/resources/rdf/i18n/es/display/firsttime/search_individuals_vivo.n3
- home/src/main/resources/rdf/i18n/fr_CA/display/firsttime/search_individuals_vivo.n3
- home/src/main/resources/rdf/i18n/pt_BR/display/firsttime/search_individuals_vivo.n3
- home/src/main/resources/rdf/i18n/ru_RU/display/firsttime/search_individuals_vivo.n3
- home/src/main/resources/rdf/i18n/sr_Latn_RS/display/firsttime/search_individuals_vivo.n3
- webapp/src/main/webapp/themes/nemo/templates/page-home.ftl
- webapp/src/main/webapp/themes/tenderfoot/templates/page/page-home.ftl
- webapp/src/main/webapp/themes/wilma/templates/page-home.ftl
[Related Vitro PR](https://github.com/vivo-project/Vitro/pull/431)
Translations for VIVO individuals presented on search results page
@chenejac Added translations for different languages. We need reviews from native speakers.
> Translations for search related individuals

- home/src/main/resources/rdf/abox/filegraph/validation.n3
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: 
- https://github.com/vivo-ontologies/vivo-ontology/issues/30 / 
- https://github.com/vivo-project/VIVO/issues/3993
Other Relevant Links (Mailing list discussion, related pull requests, etc.):
- https://wiki.lyrasis.org/display/VIVO/2024-07-03+Ontology+Interest+Group+Call
Deletes the file `validation.n3` from the `filegraph` folder.
* Removes the file validation.n3
- Activate the ORCID confirmation (https://wiki.lyrasis.org/display/VIVODOC114x/Activating+the+ORCID+integration)
- Create a profile for your
- Log into the VIVO as self-editor
- Go to your profile
- Open the tab "Identity"
- Confirm your ORCID by remote authentification via ORCID
- it should be double-checked if the deleted property and individuals are …
> Deleted validation.n3

- README.md
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: https://github.com/vivo-project/VIVO/issues/3765
Replaces a broken with a working link to the VIVO contact page.
The link to https://vivoweb.org/contact/.
* By clicking.
**Please update the following template which should be used by reviewers.**
> Fixed contact link

- webapp/src/main/webapp/templates/freemarker/edit/forms/addAssociatedConcept.ftl
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3743)**
Fixes the issue by using POST method in the form to add concepts
* Reproduce the issue
* Apply the fix
* Verify that fix fixes the issue
@hauschke @VIVO-project/vivo-committers 
1. Freemarker
> Fix for VIVO-3743

- .github/workflows/docker.yml
- Dockerfile
Removed tomcat directory from parameters provided into docker build to only create war file.
Removed line to copy vivo-home directory as it is packed inside war
> Docker build fix

- LICENSE
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**:  https://github.com/vivo-project/VIVO/issues/4035
License year is updated to 2025.
A happy new year.
Compare with calendar.
> Update LICENSE to 2025

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/docker.yml
Updated GitHub actions to fix workflows
https://github.com/actions/cache?tab=readme-ov-file#%EF%B8%8F-important-changes
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
1. GitHub workflow
> Updated GitHub actions

- webapp/src/main/webapp/WEB-INF/web.xml
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/4053)**
[Linked Vitro PR](https://github.com/vivo-project/Vitro/pull/493)
Specified application of locale selection filter on error requests.
Forward 404 errors to /page_not_found PageController
* Reproduce the problem in the issue
* Test new page_not_found error page by opening not existing page, not existing individual
@VIVO-project/vivo-committers @hauschke 
1. Java
> Customizable 404 page

- Dockerfile
- README.md
- installer/docker-example-settings.xml
- start.sh
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/4077)**
Fixes docker build
@balmas @VIVO-project/vivo-committers
1. Docker
> Docker build fixes

- webapp/src/main/webapp/templates/freemarker/visualization/personlevel/coAuthorPersonLevelD3.ftl
**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/4086)**
Fixed chord_hover function for co-author network diagram.
* Reproduce the problem in the issue
* Test that the pull request fixes the issue
1. HTML, CSS, JavaScript
> Fix for VIVO-4086
