productMods/WEB-INF/resources/startup_listeners.txt

Moved the reasonor listener to after the SearchIndexer, so that the searchindexer is started first, ensuring that it is initialized before the reasoner, so that the rebuildIndex won't throw a NullPointerException.

Start ABox recompute after searchindexer

---

productMods/WEB-INF/resources/startup_listeners.txt

Reverts vivo-project/VIVO#16 - while it might be preferable to start the search indexer before the reasoners, it is not clear that the dozen or so other initializers would not be affected by this change.

Revert "Start ABox recompute after searchindexer"

---

productMods/config/listViewConfig-authorInAuthorship.xml
productMods/config/listViewConfig-awardOrHonor.xml
productMods/config/listViewConfig-awardOrHonorGiven.xml
productMods/config/listViewConfig-degreeEarned.xml
productMods/config/listViewConfig-editorship.xml
productMods/config/listViewConfig-educationalTraining.xml
productMods/config/listViewConfig-hasClinicalActivity.xml
productMods/config/listViewConfig-hasRole.xml
productMods/config/listViewConfig-informationResourceInAuthorship.xml
productMods/config/listViewConfig-informationResourceInEditorship.xml
productMods/config/listViewConfig-orcidId.xml
productMods/config/listViewConfig-organizationForPosition.xml
productMods/config/listViewConfig-organizationForTraining.xml
productMods/config/listViewConfig-personInPosition.xml
productMods/config/listViewConfig-publicationVenueFor.xml
productMods/config/listViewConfig-publisherOf.xml
productMods/config/listViewConfig-researchActivities.xml
productMods/config/listViewConfig-researchAreaOf.xml
productMods/config/listViewConfig-roleContributesTo.xml
productMods/config/listViewConfig-roleRealizedIn.xml
rdf/display/everytime/vivoConceptDataGetters.n3
rdf/display/everytime/vivoOrganizationDataGetters.n3
src/edu/cornell/mannlib/vitro/webapp/visualization/modelconstructor/OrganizationToGrantsForSubOrganizationsModelConstructor.java
src/edu/cornell/mannlib/vitro/webapp/visualization/modelconstructor/OrganizationToPublicationsForSubOrganizationsModelConstructor.java
src/edu/cornell/mannlib/vitro/webapp/visualization/modelconstructor/PeopleToGrantsModelConstructor.java
src/edu/cornell/mannlib/vitro/webapp/visualization/modelconstructor/PeopleToPublicationsModelConstructor.java
src/edu/cornell/mannlib/vitro/webapp/visualization/modelconstructor/PersonToGrantsModelConstructor.java
src/edu/cornell/mannlib/vitro/webapp/visualization/modelconstructor/PersonToPublicationsModelConstructor.java

This partially addresses [VIVO-669](https://jira.duraspace.org/browse/VIVO-669)
Still need to find replacements for afn:localname and afn:namespace. Since they do not have analogs in the SPARQL 1.1 spec, it will likely require something a bit more complicated.
Also, I removed the afn prefix declaration from a number of listViewConfigs that did not need it (less temptation to use it in the future).

VIVO-669: remove ARQ functions `substring` and `now`

---

rdf/abox/filegraph/us-states.rdf

Add seven additional entries to the us_states.rdf file:  American Samoa, District of Columbia, Guam, Northern Mariana Islands, Puerto Rico, US Virgin Islands, Wake Island.  These are all the US territories that are occupied (the US has a number of Pacific Islands and Caribbean Islands that are not occupied).  We have received requests for the inclusion of Puerto Rico and DC.  The others have been added for completeness.
Each uses dbpedia URI.  
Tested by loading to a VIVO 1.8 Vagrant.
Addresses Jira Issue VIVO-1072

VIVO-1072 Add 7 entries to us_states.rdf

---

README.md

Updated the README.md file to remove reference to vivosearch.org.  In general, VIVO materials should not refer to future work.  Specifically, vivosearch.org is not active, and there are no plans to activate it.

Remove reference to prototype vivosearch.org

---

webapp/src/main/webapp/config/listViewConfig-authorInAuthorship.xml
webapp/src/main/webapp/templates/freemarker/body/partials/individual/propStatement-authorInAuthorship.ftl

When you have an artifact with a PMID but no DOI, the Altmetric badge isn't displayed. Technically there are two changes in one commit here, but they're both one-liners.

Fix Altmetric badge display for publications with only PMID

---

api/pom.xml
home/pom.xml
installer/home/pom.xml
installer/pom.xml
installer/solr/pom.xml
installer/webapp/pom.xml
pom.xml
webapp/pom.xml

Resolves: https://jira.duraspace.org/browse/VIVO-1479
Change project version from 2.0.0-SNAPSHOT to 1.10.0-SNAPSHOT
This is only a Maven project version change. 
Success is if the project continues to build and deploy.

Change project version from 2.0.0-SNAPSHOT to 1.10.0-SNAPSHOT

---

home/src/main/assembly/home.xml
installer/home/src/main/assembly/home.xml
installer/pom.xml
pom.xml

https://jira.duraspace.org/browse/VIVO-1470
Small corrections to the pom.xml and assembly.xml files to improve cross-platform support - remove Windows warnings and resource character set problems.
UTF-8 properties in pom files to set character set for resource filtering.
Altered assembly output directory to not use a Unix convention.
Rebuild the application, and ensure that all artefacts are created and deployed normally (e.g. there should be no visible change, other than the warnings no longer appearing on Windows)
No documentation, dependency changes or other impact.

[VIVO-1470] Cross-platform improvements for Maven

---

home/src/main/resources/rdf/tbox/filegraph/vivo.owl

**[JIRA Issue VIVO-1497](https://jira.duraspace.org/browse/VIVO-1497)**
Restores the domain assertion to the overview DatatypeProperty.  The domain is needed by VIVO to support editing in the UI.
The pull request adds annotations, providing a definition and a usage example.
Three assertions are added.  Domain, definition, and example.
To reproduce the problem, create a new person in 1.10, navigate to the person as a SiteAdmin.  You will not be able to add an Overview to the profile.  
To see that the problem is fixed, build this PR, restart Tomcat, create person, edit the person as SiteAdmin.  You will see Overview available for editing on the profile.
This pull request restores expected functionality.
@VIVO-project/vivo-committers @mjaved495 @gneissone @marijane

Add domain foaf:Agent to vivo:overview

---

home/src/main/resources/rdf/tbox/filegraph/vivo.owl

**Remove unneeded IAO_0000412 assertions from the ontology**
**[JIRA Issue 1462 ](https://jira.duraspace.org/browse/VIVO-1462)**
Small clean-up to remove assertions that have no purpose.  Of the 200+ VIVO classes, 28 had these assertions, which serve no function.
The 28 unneeded assertions have been removed.  This has no effect on the application.
Run the SPARQL query:
SELECT ?s
WHERE {
?s <http://purl.obolibrary.org/obo/IAO_0000412> <http://vivoweb.org/ontology/core> .
}
Before the pull request you will see 28 assertions.  Following a clean install of VIVO, you will see no assertions.
* Does this change require documentation to be updated? No.  The assertions are never mentioned in the documentation and have no function  in the ontology.
* Does this change add any new dependencies? No.
* …

Remove 28 IAO_0000412 assertions from vivo classes

---

webapp/src/main/webapp/config/listViewConfig-informationResourceInAuthorship.xml
webapp/src/main/webapp/templates/freemarker/body/partials/individual/propStatement-informationResourceInAuthorship.ftl

**[JIRA Issue](https://jira.duraspace.org/browse/VIVO-1603)**: https://jira.duraspace.org/browse/VIVO-1603
Fixes a problem with authors modeled as vcard:Individual
Authors modeled as vcard:Individual did not work when their names included language tags. This PR solves the problem by changing the concatenation logic and additionally adds a 'missing author' string if the name is missing.
* Reproduce the problem you are fixing (if applicable)
Add a vcard author with language tags on the name strings. 
Example name from Mike:
```
<http://vivo.mydomain.edu/individual/n1112>
a             vcard:Name ;
vcard:familyName "Veronique"@en ;
vcard:givenName "Al"@en .
```
The publication for the author will not be rendered, it will throw a Freemarker …

Fix list view and template for vCard authors

---

home/src/main/resources/rdf/tbox/filegraph/vivo.owl

[VIVO-1364](https://jira.duraspace.org/browse/VIVO-1364)
Adds a declaration that has collaborator is a symmetric object property.  This means if A has Collaborator B, then the inferencer can add B has collaborator A.
Adds four annotations to the data property to 1) define it; 2) give and example of usage; 3) provide the editor's name; 4) provide a citation for the definition.
Before this pull request, declaring A has collaborator B does not establish B as a collaborator of A.
After the pull request, the inferencer adds B is a collaborator of A.
Sites should be alerted of this change.  While the change is in keeping with common use of the term "collaborator," the provision of a new assertion is a change for VIVO.
A socialization process defines collaboration.  A and B agree that they are …

has collaborator is symmetric

---

webapp/src/main/webapp/templates/freemarker/edit/forms/addServiceProviderRoleToPerson.ftl

**[VIVO-1547](https://jira.duraspace.org/browse/VIVO-1547)**:
Fixes a bug in the create service provider role that causes the template to throw an internal server error
For a person, add a service provider role - the form to add a new role should display, and allow you to submit / create a service provider entry.
(Prior to the fix, the form would throw an error instead of displaying)

[VIVO-1547] Fix service provider template

---

installer/pom.xml
pom.xml

**[VIVO-1605](https://jira.duraspace.org/browse/VIVO-1605)**: 
Updates the pom.xml to use the latest version of Google's Error Prone plugin and configuration, so that the build works with recently released JDKs
Nothing
Do a full "mvn clean install" - the compilation should complete normally.
Should be tested with multiple JDK versions - should work for everything from JDK 8 through to the recently released JDK 11

[VIVO-1605] Update to latest Error Prone plugin and configuration to support JDK 11

---

api/src/main/java/edu/cornell/mannlib/semservices/service/impl/AgrovocService.java

**[VIVO-1655](https://jira.duraspace.org/browse/VIVO-1655)**: 
Updates broken base URL for AGROVOC REST API concept look-up. 
* To reproduce error:
1) Go to an individual profile and click "Manage list of research areas."
2) Make sure AGROVOC is selected and enter a search term (e.g. wheat). Click Search Service. 
3) Error in UI "An error was encountered in executing this search."
4) Error in vivo.all.log, similar to "ERROR [AgrovocService] Error occurred in getting concept from the URL http://artemide.art.uniroma2.it:8081/skosmos/rest/v1/search?query=animal*&lang=en"
* To test pull request:
1) Go to an individual profile and click "Manage list of research areas."
2) Make sure AGROVOC is selected and enter a search term (e.g. wheat). Click Search Service. 
3) A list of terms should …

[VIVO-1655] Updating AGROVOC REST API base URL

---

home/src/main/resources/config/example.runtime.properties

**[VIVO-1340](https://jira.duraspace.org/browse/VIVO-1340)**
Fixes links to documentation in example.runtime.properties
Removes broken links to version-specific documentation for properties. Adds link to top-level documentation page for all versions, with pointer to sections for configuration reference (recent versions) or installation properties (older versions).
Assumes that the wiki will continue to have a page listing all documentation versions. 

[VIVO-1340] Fix links to documentation in example.runtime.properties

---

pom.xml

**[VIVO-1607](https://jira.duraspace.org/browse/VIVO-1607)**:
This pull requests enables child modules to correctly template revision info build number.
The pom plugin, buildnumber-maven-plugin, was moved from release-sign-artifacts profile to the root build section. Also, the release-sign-artifacts profile was reorganized to match Vitro pom.
Deploy each strategy and ensure http://localhost:8080/vivo/revisionInfo displays correct build number. This can also be confirmed by checking under Tomcat `webapps/vivo/WEB-INF/resources/revisionInfo.txt` if deployed or under VIVO source `webapp/target/vivo-webapp-1.11.0-SNAPSHOT/WEB-INF/resources/revisionInfo.txt` if just built. The `revisionInfo.txt` file should have the correct 7 digit commit hash in replace of `${buildNumber}`.
N/A …

[VIVO-1607] corrected pom in order to template child module build number

---

webapp/src/main/webapp/templates/freemarker/edit/forms/personHasAdvisorRelationship.ftl

**[JIRA Issue](https://jira.duraspace.org/browse/VIVO-1609)**: https://jira.duraspace.org/browse/VIVO-1609
Fixes validation when adding a new advisee to a person.
Fixes a validation error, should restore lost functionality
* Reproduce the problem you are fixing (if applicable)
Go to a person's profile. Click the plus sign to add a new advisee. Neglect to select a "Advising Relationship Type" which should be required. Add a name and click 'Create enty.' This should result in the following error: 
```
There was an error in the system.
Error message: java.lang.Exception: Errors processing required N3. The EditConfiguration should be setup so that if a submission passes validation, there will not be errors in the required N3. [line: 1, col: …
```

[VIVO-1609] Fix validation on personHasAdvisorRelationship.ftl

---

home/src/main/resources/rdf/display/everytime/searchIndexerConfigurationVivo.n3

**[JIRA Issue](https://jira.duraspace.org/browse/VIVO-1671)**: https://jira.duraspace.org/browse/VIVO-1671
Restricts addition of labels to the search index for context nodes (aka faux properties).
Labels will be added to a search document for objects connected via a faux property if the property is one of the following:
Advising Relationship (vivo)
Authorship (vivo)
Awarded Degree (vivo)
Award or Honor Receipt (vivo)
Contract (vivo)
Editorship (vivo)
Grant (vivo)
Issued Credential (vivo)
Position (vivo)
which roll up to vivo:Relationship.
e.g. take this relationship:
person vivo:relatedBy authorship
authorship a vivo:Authorship
authorship vivo:relates publication
In this case, ALLTEXT in the search document for person will include the label for the publication.
vs. this relationship: …

[VIVO-1671] Restrict context node labels added to search index to relationships

---

webapp/src/main/webapp/templates/freemarker/body/partials/individual/propStatement-authorInAuthorship.ftl

**[VIVO-1676](https://jira.duraspace.org/browse/VIVO-1676)**:
Fixes problem where Plum Analytics badges incorrectly appear on publications without a recognised ID.
Create a profile with two publications:
a) An Academic Article with a DOI that shows a Plum Analytics badge
b) A DataSet, without any identifier properties set.
In the existing code, the Plum Analytics badge will be shown on both the academic article and the dataset.
With the fix applied, only the academic article will display a plum analytics badge.

[VIVO-1676] Fix for Plum Analytics badge on wrong publications

---

api/src/main/java/edu/cornell/mannlib/vitro/webapp/visualization/personlevel/PersonLevelRequestHandler.java

**[VIVO-1672(https://jira.duraspace.org/browse/VIVO-1672)**:
Fixes Null Pointer error in co-author / co-investigator graphs when accessed without parameters.
Access the plain co-author / co-vis URL - e.g.: /vis/co-author
Should report that parameters are incorrect, rather than an error in the system.
Clicking the co-author / co-investigator buttons on any profile should still result in the graph being displayed correctly.

[VIVO-1672] Fix NullPointer in visualisations

---

webapp/src/main/webapp/templates/freemarker/visualization/mapOfScience/mapOfScienceSetup.ftl

**[JIRA Issue](https://jira.duraspace.org/browse/VIVO-1677)**:  Chrome blocks Google Maps js include if site uses https
https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content
Note, I changed the link to https rather than making it protocol independent. From https://www.paulirish.com/2010/the-protocol-relative-url/ ...
> Now that SSL is encouraged for everyone and doesn’t have performance concerns, this technique is now an anti-pattern. If the asset you need is available on SSL, then always use the https:// asset.
Change the protocol of one javascript link from http to https.
Nothing
Try loading the Map of Science over https without setting the Google Maps API …

[VIVO-1677] Change legacy Google Maps link to use https

---

api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/individual/VIVOIndividualResponseBuilderExtension.java
webapp/src/main/webapp/WEB-INF/resources/startup_listeners.txt

**[VIVO-1656](https://jira.duraspace.org/browse/VIVO-1656)**:
Uses the extension mechanism to pass the Plum Analytics and AltMetric options to the individual templates.
Requires the corresponding pull request from Vitro.
No change in functionality, this is an architectural improvement.
Visit the page of any "individual" in VIVO. Should work exactly as it did before.
In particular, check publications that previously display Plum Analytics / AltMetric badges - these badges should still appear as before.

[VIVO-1656] Extension mechansim for passing properties to templates

---

webapp/src/main/webapp/themes/tenderfoot/templates/body/partials/individual/individual-visualizationFoafPerson.ftl

**[JIRA Issue](https://jira.duraspace.org/browse/VIVO-1687)**: https://jira.duraspace.org/browse/VIVO-1687
https://stackoverflow.com/questions/12830897/svg-renders-but-gets-cut-off-in-firefox-only-why
Resolves an issue where the Tenderfoot publication bar chart is cropped in Firefox 
Sets the SVG width in javascript explicitly for Firefox compatibility
Change theme to Tenderfoot. Look at bar chart in Firefox. It should be cropped in the vertical direction.
Redeploy with changes. It should show the whole chart.
@grahamtriggs

[VIVO-1687] Set Tenderfoot pub chart height

---

paper/paper.md

** Added references to JOSS paper and edited acknowledgements.
* * *
Related to: https://github.com/openjournals/joss-reviews/issues/1182
Fixing some issued from the paper review process.
References in the paper itself.
@mconlon17

Paper revision

---

webapp/src/main/webapp/config/listViewConfig-researchAreaOf.xml

Jira Issue: **[Research area display slow to load, or never loads](https://jira.duraspace.org/browse/VIVO-1704)**
Improves performance of concept pages that include 'research area of' relationship.
Nothing, this is a performance improvement 
Create a 'has research area of' relationship between a concept and a person without a position. The ?position variable is unbound, meaning you get results such as this...
Apply the fix, concepts should load much faster.
@vivo-project/vivo-committers

[VIVO-1704] - Fix unbound research area query

---

webapp/src/main/webapp/css/visualization/visualization.css

**[JIRA Issue](https://jira.duraspace.org/browse/VIVO-1733)**: VIVO-1733 
Changes a css selector so it only affects `<p>` tags within the intended visualization tools, rather than potentially all `<p>` tags on the page.
The margin is usually overwritten by wilma.css, but here is an example where it did not for a project I am working on and the visualization css was applied outside its intended scope:
Visit http://localhost:8080/vivo/vis/tools. Note 20px indent of text.
Apply change.
Visit same page. Display should be unchanged for visualization tools text.

[VIVO-1733] - Fix visualization tool css selector

---

webapp/src/main/webapp/templates/freemarker/visualization/personlevel/coAuthorPersonLevelD3.ftl
webapp/src/main/webapp/templates/freemarker/visualization/personlevel/coPIPersonLevelD3.ftl

**[JIRA Issue](https://jira.duraspace.org/browse/VIVO-1726)**: Co-author visualization: Change cursor type when hovering over link
Makes two small changes to the co-author and co-pi chord visualizations.
Change the mouse icon if a user hovers over a link in the chord diagram visualization. Additionally, link the primary author's profile page in the diagram to match the other co-authors.
View a co-author diagram. Confirm the mouse pointer icon does not change when hovering over the links on the edges of the chord diagram.
Apply change to templates. Confirm the mouse pointer changes to the 'hand' icon when hovering over links. 
Additionally, confirm that the primary person (who the visualization is created for) is now linked within the chord diagram.

[VIVO-1726] - Co-author visualization: Change cursor type when hovering over link

---

pom.xml

**[VIVO-1737](https://jira.lyrasis.org/browse/VIVO-1737)**:
Updates the Error Prone plugin to for compile time analysis to the latest release, and moves the configuration to a profile that is enabled for JDK 1.8 - 11.
Builds with Error Prone fail when using JDK 12+, so by not enabling on those JDKs enables people to use them for their environment - Vitro/VIVO builds on JDK 13, but it is not tested.
This also allows developers to disable the Error Prone plugin from the command line, however I would not recommend this in general as it quickly and easily catches bad code.
Nothing specific, although the Error Prone plugin is now faster and includes some extra checks
Run mvn clean install - build should complete.
Ideally, test with multiple JDK versions

[VIVO-1737] Update Error Prone

---

home/src/main/resources/config/example.applicationSetup.n3
home/src/main/resources/config/example.runtime.properties

Resolves: https://jira.lyrasis.org/browse/VIVO-1741
No functional changes.
This pull-request updates the example.applicationSetup.n3 file to reference a TDB triple store by default (instead of SDB).
Note: Support for SDB still exists.
Use the example.applicationSetup.n3 configuration in a new VIVO installation. 
Verify that VIVO works as expected.
Verify that content is created in the TDB "hasTdbDirectory" location.

Update example default triple store from SDB to TDB

---

home/src/main/resources/rdf/tbox/filegraph/vivo.owl

**[VIVO-1700](https://jira.lyrasis.org/browse/VIVO-1700)**:
Pull request addresses two issues:
* https://jira.lyrasis.org/browse/VIVO-1700 Collection Process
* https://jira.lyrasis.org/browse/VIVO-1699 Curation Process
Thessen, AE, Woodburn, M, Koureas, D, Paul, D, Conlon, M, Shorthouse, DP and Ramdeen, S. 2019. Proper Attribution for Curation and Maintenance of Research Collections: Metadata Recommendations of the RDA/TDWG Working Group. Data Science Journal, 18: 54, pp. 1–11. DOI: https://doi.org/10.5334/dsj-2019-054
Adds two new classes to the VIVO ontology: CurationProcess and CollectionProcess 
To represent that Jane is the Collector of a particular Collection z, we say Jane has a CollectorRole, the role is …

Add CollectionProcess and CurationProcess

---

api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddReviewerRoleToPersonGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/GeneratorUtil.java

Resolves: https://jira.lyrasis.org/browse/VIVO-1774
- Fixes a type in the constant "describe-query" of AddReviewerRoleToPersonGenerator
- Updates related variable names to use standard Java syntax
Test steps detailed in description of: https://jira.lyrasis.org/browse/VIVO-1774
@MichelHeon / @VIVO-project/vivo-committers

Fix typo in AddReviewerRoleToPersonGenerator

---

api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddOutreachProviderRoleToPersonGenerator.java

Resolves: https://jira.lyrasis.org/browse/VIVO-1775
- Fixes a typo in the constant "describe-query" of AddOutreachProviderRoleToPersonGenerator
@MichelHeon @VIVO-project/vivo-committers

Fix typo in AddOutreachProviderRoleToPersonGenerator

---

installer/home/pom.xml
installer/webapp/pom.xml
webapp/src/main/webapp/WEB-INF/resources/startup_listeners.txt

Move "LocaleSelectionSetup" higher in the startup list so that the Vitro:RDFFilesLoader has the locale info available on its startup
See https://github.com/vivo-project/Vitro/pull/160 for full details
* https://github.com/vivo-project/Vitro-languages/pull/18
* https://github.com/vivo-project/VIVO-languages/pull/41
* https://github.com/vivo-project/Vitro/pull/160
Part of resolution to: https://jira.lyrasis.org/browse/VIVO-1836

Include language dependencies in build all of the time

---

webapp/src/main/webapp/i18n/vivo_all.properties
webapp/src/main/webapp/js/visualization/capabilitymap/graph_new.js
webapp/src/main/webapp/templates/freemarker/visualization/capabilitymap/capabilityMap.ftl

**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1847)**
**[Second required PR](https://github.com/vivo-project/VIVO-languages/pull/56)**
The PR will add multi-language support for a part of the capability map and the title of the site.
This PR will add two variables for the multi-language support in the needed js-file and use them. If they are not provided by the languashould this be tested?
You go to the capability map, search for something (with sample data for example "Rhetoric") and then click the "informations" Button. The Group and the Term should be multi-lingual. Just like the title of the page.
* the multi-language tags come with another PR in the VIVO-languages Repository
**Note:** Ignore the name of the branch, i accidentally used the number of my other ticket. 1847 would …

i18n: title tag and headings in capability map are in english in french version

---

webapp/src/main/webapp/i18n/vivo_all.properties
webapp/src/main/webapp/js/visualization/capabilitymap/graph_new.js
webapp/src/main/webapp/templates/freemarker/visualization/capabilitymap/capabilityMap.ftl

**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1846)**
**[2nd related PR](https://github.com/vivo-project/VIVO-languages/pull/58)**
This PR will add i18n support for the Capability Map control buttons
Now the control buttons (and the functionality behind it) use i18n properties and because of that are multilingual.
* added 6 new i18n strings to property-file
* added them to the JS-file and use them for the label and also for the button functionality (for example switch pause <-> resume)
* Go to the Capability Map
* search a existing term (for sample data "Rhetoric" is available)
* all buttons (pause <-> resume, hide group labels <-> show group labels, expand, remove group, remove capability, delete selected) should be in all 6 existing languages in VIVO-Languages  
** to see "resume" …

[VIVO-1846] i18n: Added i18n support for Capability Map control buttons

---

webapp/src/main/webapp/js/visualization/capabilitymap/graph_new.js
webapp/src/main/webapp/templates/freemarker/visualization/capabilitymap/capabilityMap.ftl

**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1892)**
**[2nd related PR](https://github.com/vivo-project/VIVO-languages/pull/61)**
With this PR all text from the Capability Map template is replaced with i18n-properties und pull into the property-file.
In addition the property-files for the Capability Map in VIVO-languages will be updated and the language specific templates in VIVO-languages will be deleted.
Only a single i18n compatible template for the capability map instead of one for each language
Go to the capability map and switch between languages, everything should be translated.

[VIVO-1892] i18n: added i18n support for the capability map

---

api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddRoleToPersonTwoStageGenerator.java

Partial resolution to: https://jira.lyrasis.org/browse/VIVO-1881
Adds an I18NBundle parameter to `FieldOptions` so that drop-down lists may be translated.
1. Go to person/individual
1. Select the "Teaching" tab
1. Select "advisees"
1. View "Advising Relationship Type" dropdown list
- Verify the term "Other" is translated
- https://github.com/vivo-project/Vitro/pull/171

Ensure 'other' in Individual->Teaching->advisees->type is translated

---

home/src/main/resources/config/example.applicationSetup.n3

Related to: https://jira.lyrasis.org/browse/VIVO-1741
Updates a comment in example.applicationSetup.n3 to note TDB as default triplestore
No functional changes

Non-functional change to comment in example.applicationSetup.n3

---

api/src/main/java/org/vivoweb/webapp/startup/i18nSetup.java
webapp/src/main/webapp/WEB-INF/resources/startup_listeners.txt

**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1924?src=confmacro)**
This PR fixes the bug described in the ticket by rearranging the startup-listeners. 
Test the Bug:
- When starting VIVO for the very first time, i18n strings in English are not loaded. The 'theme' strings are loaded, but the top level all.properties are not. If the i18n cache is disabled, then the strings immediately appear. 
- Start your vivo (with english enabled in runtime.properties) for the first time and visit the main page (language set to en-US), there should be some missing variables (see images in JIRA-Ticket)
Test the fix:
- apply changes
- Start your vivo (with english enabled in runtime.properties) for the first time and visit the main page, everything should look normal and no missing variables
Note: …

[VIVO-1924] i18n: @en i18n properties are not loaded during first site startup.

---

webapp/src/main/webapp/templates/freemarker/edit/forms/addEditorshipToPerson.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/addPublicationToPerson.ftl

**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1831)**: i18n : In "Create publication" form, dropdown menu has duplicate item
Fixes an issue where both 'select a type' and 'select one' appeared in dropdown menus.
Simply removes the offending text string reference from two template files.
On sprint i18n branch, either click the plus sign next to 'selected publications' or 'editor of' on a person's profile page. Confirm you see both 'select a type' and 'select one' in the publication type dropdown. 
Apply patch. Confirm only 'select a type' appears.
Did not find any other forms that were affected by this, though there certainly are other forms that use the 'select one' logic for the dropdown. The logic appeared when the [buildResourceAndLabelFieldOptions](https://github.com/vivo-project …

[VIVO-1831] - Remove duplicate text from dropdown menus

---

api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/FirstAndLastNameValidator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddEditorsToInformationResourceGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/GrantHasContributorGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/OrganizationForTrainingGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/OrganizationHasPositionHistoryGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/PersonHasAdviseeRelationshipGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/PersonHasAdvisorRelationshipGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/ProjectHasParticipantGenerator.java

**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1798) **: [i18n: english dropdown elements and error messages in french version of 'Create position history entry for nXXXX'](https://jira.lyrasis.org/browse/VIVO-1798)
Internationalizes hard-coded English in the first and last name validation class.
Passes context to FirstAndLastNameValidator.java so it can determine the proper i18n string to display
3 strings added to all languages, which were previously hard-coded in English in FirstAndLastNameValidator.java.
See https://jira.lyrasis.org/browse/VIVO-1798 for process to confirm issue.
Deploy changes, including those in the [companion PR](https://github.com/vivo-project/VIVO-languages/pull/84) at VIVO-languages. Replicate process and confirm the proper language is displayed. Note, you …

[VIVO-1798] - Internationalize first and last name validation

---

.github/workflows/docker.yml
Dockerfile

Resolves [VIVO-1961](https://jira.lyrasis.org/browse/VIVO-1961)
Simple GitHub action workflow and Dockerfile to build VIVO tomcat image and publish to [vivoweb/vivo](https://hub.docker.com/r/vivoweb/vivo)
`Dockerfile` and `.github/workflows/deploy.yml`
The Dockerfile can be tested locally following these commands with Docker installed.
```
mvn clean install
docker build --no-cache -t vivo .
docker run -p 8080:8080 vivo
```
Or using the published image with a single command.
```
docker run -p 8080:8080 vivoweb/vivo:latest
```
Then navigate the browser to http://localhost:8080. You should see VIVO running as root Tomcat webapp. It will not have search functionality.
Solr and database sold separately.

VIVO-1961: GitHub Action to Publish Docker Image

---

webapp/src/main/webapp/templates/freemarker/visualization/publication/personPublicationCountNoSparkline.ftl
webapp/src/main/webapp/templates/freemarker/visualization/publication/personPublicationSparklineContent.ftl

Resolves https://jira.lyrasis.org/browse/VIVO-1814
It is a known issue that some properties containing single quotes can cause conflict when Javascript is inserted into ftl files, hence the need to use the `js_string` builtin to escape problematic characters (see https://jira.lyrasis.org/browse/VIVO-1842). 
In the two files modified in this PR, however, the conflict occurs in the html written by the Javascript, where the single quotes are displayed in the attributes of an `img` tag.
> ![image](https://user-images.githubusercontent.com/46490666/106614354-3ca63980-6539-11eb-82f6-305f1ed7a6ec.png)
In [Freemarker >2.3.24](https://freemarker.apache.org/docs/ref_builtins_string.html#ref_builtin_html), those special characters are automatically escaped as ascii codes. However, if VIVO is …

Escaping single quotes as ascii codes in publication count .ftl

---

home/src/main/resources/rdf/display/everytime/searchIndexerConfigurationVivo.n3

**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1911)**: VIVO-1911 ALLTEXT field in search index not as robust as before
Hopefully fixes an issue where labels of relevant object connected via faux properties are not added to the search index's ALLTEXT field.
A reversion of functionality without re-introduction of overzealous indexing.
Confirm current behavior: Assuming VIVO database has person connected to a publication, inspect search index record for person. The ALLTEXT field will not have the publication label included.
Deploy fix. Repeat procedure, confirm ALLTEXT field includes publication text.
@brianjlowe  @VIVO-project/vivo-committers

[VIVO-1911] - Bugfix for type restriction in search index config

---

webapp/src/main/webapp/themes/tenderfoot/templates/page/page-home.ftl
webapp/src/main/webapp/themes/tenderfoot/templates/page/page.ftl
webapp/src/main/webapp/themes/wilma/templates/page-home.ftl
webapp/src/main/webapp/themes/wilma/templates/page.ftl

**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1343)**
Companion Vitro pull request: https://github.com/vivo-project/Vitro/pull/228
Uses the existing (if oddly-named) "country" value supplied by FreemarkerHttpServlet to populate HTML lang and xml:lang values.  Replaces hardcoded "en" value.
Test that value (visible at top of page source) changes properly with language selection in both Wilma and Tenderfoot on both the home page and other pages.  Test also with no language filtering enabled or a forced locale.
Some pages that are not generated via the standard Freemarker stack (e.g. smoke tests, goToIndividual.jsp and other JSPs) have not been modified.  As these are not crawled by search engines and are used only by admins, the consequences of incorrect tags are probably minimal. …

Replace hardcoded en locale with current locale in lang attributes

---

home/src/main/resources/config/example.runtime.properties

**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1974)**: 
Companion Vitro PR: https://github.com/vivo-project/Vitro/pull/220
https://wiki.lyrasis.org/display/VIVO/2021-03-23+-+VIVO+Development+IG
Updates example.runtime.properties to include listview.usePreciseSubqueries control.
Other considerations:
* Installation documentation will likely need updating to include this setting.

Add usePreciseSubqueries property to example.runtime.properties with default to true

---

home/src/main/resources/config/example.runtime.properties

**[JIRA Issue](https://jira.lyrasis.org/browse/VIVO-1982)**: https://jira.lyrasis.org/browse/VIVO-1982
Changes default email parameters to a blank value, which disables the Contact us form and prevents a warning from being thrown on initial start up.
Deploy change, ensure VIVO starts without smoke test warning about email server being disabled.
Previously merged as part of https://github.com/vivo-project/VIVO/pull/214/files but lost to the sands of time and reversions.

[VIVO-1982] - Set default email params to blank

---

installer/example-settings.xml
pom.xml

VIVO-Languages and Vitro-Languages in VIVO
This PR allows to integrate the compilation of (VIVO/Vitro)-Languages with VIVO in a single Maven call
No Jira Issue 
Modification of pom.xml and example-settings.xml
Example:
- rename examples-settings.xml to settings.xml
- follow the instructions inside the settings.xml file
- Execute maven (mvn -s installer/settings.xml clean install
Extract RC-1.12.0 all 4 repos (VIVO, Vitro and languages)

integrate in a single Maven call the compilation and installation of

---

Dockerfile
installer/home/pom.xml
installer/webapp/pom.xml

**[Issue](https://github.com/vivo-project/VIVO/issues/3610)**: resolves https://github.com/vivo-project/VIVO/issues/3610
Re-adds language dependencies into pom.xml files. VIVO and Vitro languages must now always been included, even when using VIVO with a single language.
Follow instructions on how to install VIVO at https://wiki.lyrasis.org/display/VIVODOC112x/Installing+VIVO. If VIVO installs and does not complain about missing language files or strings upon startup, it was a success. 
@roflinn

Uncomment missing language dependencies

---

webapp/src/main/webapp/templates/freemarker/lib/lib-microformats.ftl

**[JIRA Issue](https://github.com/vivo-project/VIVO/issues/3612)**: Fixes #3612 
https://groups.google.com/g/vivo-tech/c/PEIjS7kuIeY/m/odmwhKXeBwAJ
Prevents a Freemarker error encountered in rare cases.
Adds blank fallback in case of issue retrieving a most specific type value within the lib-microformats.ftl file.
Search an individual's page source for a microformat value, e.g. `itemscope itemtype="http://schema.org/Thing"` before applying change. After applying change, you should still see the microformat value on the page... but it should also prevent a freemarker error from being thrown in case the macro was unable to find a most specific type (for whatever reason...). 
Unfortunately I don't know exactly why …

Fallback in case of missing most specific type for microformat macro

---

installer/home/pom.xml

Changes artifact type from pom to tar.gz to prevent copying pom files ( vitro-languages-home-core-1.12.3-SNAPSHOT.pom
and vivo-languages-home-core-1.12.3-SNAPSHOT.pom ) to home directory.
**How to test**
Install VIVO from sources before applying, notice that files are added to home directory.
Clean home directory
Apply this PR
Install VIVO from sources, verify that files are not added to home directory

Prevent copying pom files to home directory

---

home/src/main/resources/rdf/display/everytime/homePageDataGetters.n3
home/src/main/resources/rdf/display/everytime/vivoConceptDataGetters.n3
home/src/main/resources/rdf/display/everytime/vivoOrganizationDataGetters.n3
webapp/src/main/webapp/templates/freemarker/body/partials/individual/individual-affiliated-dept-details.ftl
webapp/src/main/webapp/templates/freemarker/body/partials/individual/individual-affiliated-res-area-details.ftl
webapp/src/main/webapp/templates/freemarker/body/partials/individual/individual-dept-active-grants.ftl
webapp/src/main/webapp/templates/freemarker/body/partials/individual/individual-dept-res-area-details.ftl

[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3723) 
Fixes for pages
/affiliatedDepartments
/affiliatedResearchAreas
/deptResearchAreas
/deptGrants
Add sample data, view pages listed above, click individual links, 
verify that links are working even if individual is not from default namespace for that instance.
On [example of concept page ](https://vivo.tib.eu/vivo113rc/individual?uri=http://localhost:8080/vivo_i18n/individual/n5504) should be associated department only in one language.
Applied on https://vivo.tib.eu/vivo113rc

Multiple fixes for VIVO pages

---

api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddAssociatedConceptGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddAuthorsToInformationResourceGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddEditorsToInformationResourceGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddEditorshipToPersonGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddFullNameToPersonGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddGrantRoleToPersonGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddPresenterRoleToPersonGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddPublicationToPersonGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddRoleToPersonTwoStageGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddUserDefinedConceptGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/GrantAdministeredByGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/GrantHasContributorGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/OrganizationAdministersGrantGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/OrganizationForTrainingGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/OrganizationHasPositionHistoryGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/PersonHasAdviseeRelationshipGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/PersonHasAdvisorRelationshipGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/PersonHasAwardOrHonorGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/PersonHasEducationalTraining.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/PersonHasIssuedCredentialGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/PersonHasPositionHistoryGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/PersonHasPreferredTitleGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/ProjectHasParticipantGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/SubjectHasMailingAddressGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/SubjectHasPhoneFaxNumberGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/VIVODefaultAddMissingIndividualFormGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/VIVONewIndividualFormGenerator.java
home/src/main/resources/rdf/tbox/filegraph/vivo.owl

[GitHub Issue](https://github.com/vivo-project/VIVO/issues/3717)
Goes with [PR](https://github.com/vivo-project/Vitro/pull/296)
Fixed N3 Generators to save rdf:langString literals with language tags instead of xsd:string. 
Removed xsd:string ranges from data properties:
http://www.w3.org/2006/vcard/ns#givenName
http://www.w3.org/2006/vcard/ns#familyName
http://www.w3.org/2006/vcard/ns#honorificSuffix
http://www.w3.org/2006/vcard/ns#honorificPrefix
http://www.w3.org/2006/vcard/ns#locality
http://www.w3.org/2006/vcard/ns#streetAddress
http://www.w3.org/2006/vcard/ns#country
http://www.w3.org/2006/vcard/ns#region
http://www.w3.org/2006/vcard/ns#title
http://vivoweb.org/ontology/core#supplementalInformation
For each of modified generators:
1. Creating individuals
2. Verify that created …

i18n N3 Generators fixes

---

home/src/main/resources/rdf/display/firsttime/PropertyConfig.n3

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3733](https://github.com/vivo-project/VIVO/issues/3733)
Adding rights to editor and site admin for editing grant contributors from the grant individual page
1. Log in as a root user
2. Create an editor
3. Log in as an editor
4. Open a person profile page
5. Click on Research tab
6. Click on plus next to Investigator and add a grant
7. Click on the grant link (a grant individual page will be open)
8. Click on the tab Affiliation
9. Click on the plus sign next to the contributors and add a contributor 
1. Log in as a root user
2. Create a site admin
3. Log in as site admin
4. Open a person profile page
5. Click on Research tab
6. Click on plus next to Investigator and add a grant
7. Click on the grant link (a grant …

Privilages for editing grant contributors

---

webapp/src/main/webapp/templates/freemarker/edit/forms/addConceptThroughObjectPropertyAutoComplete.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/addEditorshipToPerson.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/addGrantRoleToPerson.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/addPresenterRoleToPerson.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/addPublicationToPerson.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/addRoleToPersonTwoStage.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/addUserDefinedConcept.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/autoCompleteDataPropForm.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/grantAdministeredBy.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/grantHasContributor.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/js/customFormWithDataAutocomplete.js
webapp/src/main/webapp/templates/freemarker/edit/forms/organizationAdministersGrant.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/organizationForTraining.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/organizationHasPositionHistory.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/personHasAdviseeRelationship.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/personHasAdvisorRelationship.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/personHasAwardOrHonor.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/personHasEducationalTraining.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/personHasIssuedCredential.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/personHasPositionHistory.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/projectHasParticipant.ftl

[Companion Vitro-languages PR](https://github.com/vivo-project/Vitro-languages/pull/64)
[Companion Vitro PR](https://github.com/vivo-project/Vitro/pull/338)
Use language-neutral selectAnExistingOrCreateNewOne translation key as help text in forms with auto-completion
Try out forms with auto-completion to see new text
@tawahle

[i18n sprint] Language-neutral help text in autocomplete forms

---

webapp/src/main/webapp/templates/freemarker/edit/forms/addEditorRoleToPerson.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/addRoleToPersonTwoStage.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/defaultAddMissingIndividualForm.ftl
webapp/src/main/webapp/templates/freemarker/lib/lib-vivo-form.ftl

[Companion PR VIVO-languages](https://github.com/vivo-project/VIVO-languages/pull/116)
[Companion PR Vitro](https://github.com/vivo-project/Vitro/pull/336)
[Companion PR Vitro-languages](https://github.com/vivo-project/Vitro-languages/pull/63)
This pull request is one of many efforts to improve language neutral Freemarker templates and thus eliminate the need to support language specific templates
Imported fixes from language specific 
https://github.com/vivo-project/VIVO-languages/pull/116/files#diff-bf3f484c537ac9a4842a00b9fd05fa8a5b2736a063d227ea267a4a41a234e1c1
https://github.com/vivo-project/VIVO-languages/pull/116/files#diff-78d57e69e61fc3f97b28ce03f1e1880b2defb2cd999c4c78cdc90c1df272f430
https://github.com/vivo-project/VIVO-languages/pull/116/files#diff-c426a780340d83909740bb200dd88 …

[ i18n sprint ] I18n fixes for edit forms

---

webapp/src/main/webapp/templates/freemarker/edit/forms/addEditWebpageForm.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/addPresenterRoleToPerson.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/grantHasContributor.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/organizationForTraining.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/personHasEducationalTraining.ftl
webapp/src/main/webapp/themes/nemo/i18n/all.properties

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3748)**
[Companion VIVO-languages PR](https://github.com/vivo-project/VIVO-languages/pull/112)
[Companion Vitro PR](https://github.com/vivo-project/Vitro/pull/328)
Removed check for "Other" special case. Removed unused translations.
Verify that described issue is no longer reproducible after this fix applied.
Verify forms:
- Add webpage for individual
- Add presenter role to person (described in the issue)
- Add education and training to person
- Add contributor to grant
- Add organization for training to organization

[ i18n sprint ] VIVO-3748 Remove "Other" special case from ChildVClassesWithParent

---

webapp/src/main/webapp/config/listViewConfig-webpage.xml

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3793)**
Fixes query to use language filtering for website links in profiles
* Create person profile
* Add website link, switch language, edit link label
* Verify that only one label is shown on profile's page.
@tawahle @chenejac @bkampe

[i18n] Query fix to use language filtering for website links in profiles

---

api/src/main/java/edu/cornell/mannlib/vitro/webapp/visualization/utilities/VisualizationCaches.java

Added null checks in visualisation caches to prevent NPEs in case labels aren't exist or exists but not literals.
* Load  [broken_data.n3.zip](https://github.com/vivo-project/VIVO/files/9952902/broken_data.n3.zip)
* Verify that capability map is working

Improved safety for visualisation cahes queries.

---

webapp/src/main/webapp/js/individual/individualUtils.js
webapp/src/main/webapp/templates/freemarker/body/individual/individual--foaf-person-2column.ftl
webapp/src/main/webapp/themes/nemo/templates/individual--foaf-person.ftl
webapp/src/main/webapp/themes/tenderfoot/templates/body/individual/individual--foaf-person.ftl
webapp/src/main/webapp/themes/wilma/templates/individual--foaf-person.ftl

Fixes export_qr_code translation on hover of qr code image
For vitro, wilma, nemo, tenderfoot themes:
* Open person profile
* Click on qr code icon image
* Hover over enlarged qr code image
* Verify that Export qr code hint is shown
@chenejac

fixed export_qr_codes translation

---

api/src/main/java/edu/cornell/mannlib/semservices/service/impl/AgrovocService.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/ManageWebpagesForIndividualGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/visualization/utilities/VisualizationCaches.java

**[Issue #3767 Problems associated with the use of sparqlContentTripleSource in the applicationSetup.n3 configuration file](https://github.com/vivo-project/VIVO/issues/3767)**: 
This PR fixes the language context management issue in the Capability Map when using VIVO which uses AWS-Neptune TripleStore
As described in the issue, VIVO's CapabilityMap using AWS-Neptune as a TripleStore is not working properly. The malfunction is related to the disfunction of the expertise search bar. The cause of this malfunction is that, unlike the other triple stores, the linguistic value of the tags is stored in lower case. For example: the term "Label"@en-CA is actually stored in AWS-Neptune as "Label"@en-ca. 
The solution is to modify the SPARQL queries in the Java code so that the filters process the …

[Issue 3767] Replacement of language comparisons using '=' by the 'langMatches' (without whitespace changes)

---

api/src/main/java/edu/cornell/mannlib/semservices/service/impl/AgrovocService.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/ManageWebpagesForIndividualGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/visualization/utilities/VisualizationCaches.java

**[Issue #3767 Problems associated with the use of sparqlContentTripleSource in the applicationSetup.n3 configuration file](https://github.com/vivo-project/VIVO/issues/3767)**: 
This PR fixes the language context management issue in the Capability Map when using VIVO which uses AWS-Neptune TripleStore
As described in the issue, VIVO's CapabilityMap using AWS-Neptune as a TripleStore is not working properly. The malfunction is related to the disfunction of the expertise search bar. The cause of this malfunction is that, unlike the other triple stores, the linguistic value of the tags is stored in lower case. For example: the term "Label"@en-CA is actually stored in AWS-Neptune as "Label"@en-ca. 
The solution is to modify the SPARQL queries in the Java code so that the filters process the …

Replacement of language comparisons using '=' by the 'langMatches'

---

home/src/main/resources/config/example.runtime.properties
webapp/src/main/webapp/templates/freemarker/body/individual/individual--foaf-organization.ftl
webapp/src/main/webapp/themes/nemo/templates/individual--foaf-organization.ftl
webapp/src/main/webapp/themes/nemo/templates/individual-custom-visualizationFoafPerson.ftl
webapp/src/main/webapp/themes/tenderfoot/templates/body/partials/individual/individual-visualizationFoafPerson.ftl

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3821](https://github.com/vivo-project/VIVO/issues/3821)
Other Relevant Links (Mailing list discussion, related pull requests, etc.)
* Requires [Vitro PR 373](https://github.com/vivo-project/Vitro/pull/373)
Add an option to not show (disable) Map of Science Visualization link in the same manner as done with the Temporal Visualization link.
All themes and base template are updated accordingly.
* A new runtime property `visualization.mapOfScience` is added with the default set to `disabled`.
* Each theme is updated to handle either Map of Science Visualization or Temporal Visualization being `enabled` or `disabled` via the runtime configuration.
Change the setting to enabled and disabled and check each theme to confirm …

VIVO 3821: Add configuration to disable or enable Map of Science visualization.

---

webapp/src/main/webapp/themes/tenderfoot/templates/body/partials/individual/individual-visualizationFoafPerson.ftl

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3850](https://github.com/vivo-project/VIVO/issues/3850)
Fix a small issue with non-closed if statement in an ftl file.
Fixed closing statement for tenderfoot individual-visualizationFoarPerson.ftl
- build VIVO
- switch to tenderfoot theme (VIVO_HOME/rdf/applicationMetadata/firsttime/initialSiteConfig.rdf, replace wilma with tenderfoot)
- run VIVO
- ingest sample data
- click on Bogart Andrew (person)
- the person profile page should be displayed without any error

[3850] fixing not closed if statement

---

home/src/main/resources/rdf/display/firsttime/PropertyConfig.n3

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3865)**
Sets domain for participant faux property to obo:Process.
* Create a project, at least one person
* Click add participant in project, select person.
* Verify that person is saved, list view is showing person.
@tawahle  @brianjlowe @chenejac

Set faux property 'participant' domain to obo:Process

---

installer/home/pom.xml

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3855](https://github.com/vivo-project/VIVO/issues/3855)
Fixing a bug introduced by this [PR](https://github.com/vivo-project/VIVO/pull/3802/files#diff-f6ff34b05a4edd01967c9fec8efcb5430bbd24a181cf95af2f75ddd600c82c2f). It will be probably irrelevant after merging this [PR](https://github.com/vivo-project/Vitro/pull/370), but we should fix this meanwhile.
- configure setting.xml (for instance VIVO/installer/example-settings.xml) to point to an empty VIVO_HOME directory
`<vivo-dir>/opt/VIVO/home1111</vivo-dir>`
- mvn clean install -s installer/example-settings.xml
- it should be successfully completed

fixing the issue with removing vivo_home/rdf directory

---

webapp/src/main/webapp/templates/freemarker/body/partials/individual/individual-contactInfo.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/autoCompleteDataPropForm.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/personHasEmailAddress.ftl

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3869)**
[Vitro PR](https://github.com/vivo-project/Vitro/pull/388)
Fixes some freemarker templates to avoid invalid html.
1. Create  individual with Label `Create data property with value </div>"</div>`
2. Add primary email address to a profile with a text `</div>"</div>`
3. Verify that profile page is not broken
4. Try to delete email address, verify that delete page is not broken.

Escape html values

---

api/src/main/java/edu/cornell/mannlib/vitro/webapp/visualization/capabilitymap/CapabilityMapRequestHandler.java

Limits callback to only ipretFullResults and ipretResults values
* Build and install VIVO
* Load sample data
* Open capability map
* Enter Civil War Reconstruction
* Capability map should work
* Try using the url described in the slack thread
/visualizationAjax?vis=capabilitymap&query=291822&callback=ipretResultsoesic<script>alert(1)<%2fscript>cwz3i&noCacheIE=1687235208332
* Alert in the browser shouldn't appear.
Slack discussion https://vivo-project.slack.com/archives/C8RL9L98A/p1687378615914659

Limit callback to only ipretFullResults and ipretResults values

---

.github/workflows/codeql-analysis.yml

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3902](https://github.com/vivo-project/VIVO/issues/3902)
* https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
Upgrading the codeql-action version (v1 is deprecated, it is upgraded to v2)
codeql-analysis.yml files is slightly changed
https://github.com/vivo-project/VIVO/actions/runs/5690776782 there shouldn't be errors present in the previous running of codeql action, such as https://github.com/vivo-project/VIVO/actions/runs/5630429939

Codeql action upgrade

---

webapp/src/main/webapp/js/visualization/capabilitymap/graph_new.js

Fixes the unresponsive behavior of capability map nodes in the Nemo theme when clicked. The issue stemmed from an incorrect jQuery selector used in the theme's jQuery version.
Resolved the jQuery selector issue by adding single quotes to the value of the href attribute:
$(".titles li a[href='#" + name + "']")...
1. Open the Capability Map tab.
2. Search for an item.
3. Click on a node to verify if it opens the information tab on the right side.
4. Test this across all themes for thorough validation.

Fixed jquery selector for capability map tabs

---

home/src/main/resources/rdf/display/everytime/searchFieldsConfigurationVivo.n3

In case data contain multiple ranges it prevents document modifier from sending multiple ranges to the same search field, which doesn't support multiple ranges.

Fix for dates document modifier

---

api/src/main/java/org/vivoweb/webapp/controller/freemarker/CreateAndLinkResourceController.java
home/src/main/resources/config/example.applicationSetup.n3
webapp/src/main/webapp/WEB-INF/resources/startup_listeners.txt

**[VIVO GitHub issue 1](https://github.com/vivo-project/VIVO/issues/3135)**
**[VIVO GitHub issue 2](https://github.com/vivo-project/VIVO/issues/3832)**
[Vitro PR](https://github.com/vivo-project/Vitro/pull/390)
The pull request adds a module that enables tracking of changes being made in the triple store by users and non-person entitites.
Changes are recorded in a triple store, with the users ID (URI), the time, and the changes that have been made.
A user interface (/audit) is also provided that, when logged in, displays the changes.
Adds a new AuditModule application module
TDBAuditModule can be configured / enabled via the applicationSetup.n3
RDFService change listener capture any changes made to the content and configuration stores, and record those changes in a dedicated audit store. …

Audit module (Change Tracking)

---

home/src/main/resources/config/example.runtime.properties

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [Mitigate vulnerability of Captcha feature](https://github.com/vivo-project/VIVO/issues/3918)
[Vitro PR](https://github.com/vivo-project/Vitro/pull/427)
Adds captcha configuration example. This VIVO PR goes in pair with [this Vitro PR](https://github.com/vivo-project/Vitro/pull/427).
@chenejac @brianjlowe @litvinovg

Added captcha configuration example.

---

webapp/src/main/webapp/themes/wilma/css/wilma.css

Solves: #3933
This pull request updates the frontend components affected by the integration of Bootstrap into the Wilma theme in PR #3909.
Compare pages in the old Wilma theme with the updated version.
The theme should remain mostly similar but with added responsiveness.
After update:

Fixing Wilma responsive theme update

---

api/src/main/java/org/vivoweb/webapp/controller/freemarker/CreateAndLinkResourceController.java

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3959)**
Fixes imported date precision.
Store imported date precision as a resource, not string literal.
* Reproduce the problem in the issue
* Test that the pull request resolves the issue

Store precision as a resource on DOI claiming

---

.env
.gitignore
Dockerfile
README.md
docker-compose.yml
start.sh

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: https://github.com/vivo-project/VIVO/issues/3939
This PR provides more configurability for docker compose and build of the VIVO docker image. Primarily addressing port mapping configuration via `.env` file for `docker-compose.yml` variable substitution.
1. solr and tomcat service port mapping configurable via `.env`
2. ability to specify VIVO home path within the container
3. local mount for VIVO solr core data to persist through container restarts
This can be tested by following https://github.com/wwelling/VIVO/blob/issue-3939/README.md#docker-compose. For more exhaustive testing the `.env` file can be modified between container restarts for desired effect.
@chenejac, @isl3

Improved docker setup

---

webapp/src/main/webapp/themes/wilma/css/wilma.css

Reverts vivo-project/VIVO#3932

Revert "Fixing Wilma responsive theme update"

---

webapp/src/main/webapp/js/individual/individualUtils.js
webapp/src/main/webapp/js/visualization/visualization-helper-functions.js
webapp/src/main/webapp/templates/freemarker/body/partials/individual/individual-qrCodeGenerator.ftl
webapp/src/main/webapp/templates/freemarker/visualization/coauthorship/coAuthorshipSparklineContent.ftl
webapp/src/main/webapp/templates/freemarker/visualization/copi/coInvestigationSparklineContent.ftl
webapp/src/main/webapp/templates/freemarker/visualization/grant/personGrantSparklineContent.ftl
webapp/src/main/webapp/templates/freemarker/visualization/publication/personPublicationCountNoSparkline.ftl
webapp/src/main/webapp/templates/freemarker/visualization/publication/personPublicationSparklineContent.ftl

**[VIVO GitHub issue 3973](https://github.com/vivo-project/VIVO/issues/3973)**
Fixes Google Chart API
Google chart API for generating QR code is replaced with quickchart.io.
Google Chart Sparkline image has been replaced with a Google LineChart due to the discontinuation of the Google API Chart API server, which is no longer available for generating images (Line Chart generates SVG locally). Graphs are configured to be identical as they were before.
Fixed no chart view (only text) mode. There was a problem with loading libraries.
The chart on hover shows detailed info
* Open any individual profile page (that has at least 1 publication in the last 10 years)
* Check if the publication graph is shown on the right side
* Open **Co-author Network** and check if publciations and co-authors …

Fixes Google Image Line Chart

---

home/src/main/resources/rdf/accessControl/firsttime/profile_proximity_query.n3

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3945)**
[Vitro PR](https://github.com/vivo-project/Vitro/pull/444)
Fixes broken profile linking made by using External Auth ID.
- Refactored PolicyHelper and AuthorizationRequest to use UserAccount instead of of IdentifierBundle.
- Modified SparqlSelectQueryResultsChecker to support queries that contain externalAuthId and matchingPropertyUri
- Modified existing policies to find related profiles by using External Auth ID
* Reproduce the problem described in the issue
* Apply Vitro PR and this PR, build VIVO
* Create a self editor user account and 2 profiles, link user account with one of created profiles by using External Auth ID
* In both profiles …

Support self editor profile matching by using External Auth ID

---

webapp/src/main/webapp/themes/tenderfoot/css/screen.css

[Vitro PR](https://github.com/vivo-project/Vitro/pull/465)
Updated Tenderfoot theme to use local fonts instead of retrieving from cloud.
* Select Tenderfoot theme
* Open home page
* Open web instruments, reload page, see that local fonts are being downloaded
@hauschke 
1. Web development

Use local Noto Sans in Tenderfoot theme

---

home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_admin_add_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_admin_display_data_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_admin_display_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_admin_drop_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_admin_edit_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_curator_add_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_curator_display_data_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_curator_display_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_curator_drop_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_curator_edit_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_editor_add_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_editor_display_data_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_editor_display_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_editor_drop_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_editor_edit_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_public_display_data_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_public_display_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_self_editor_add_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_self_editor_display_data_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_self_editor_display_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_self_editor_drop_object_property.n3
home/src/main/resources/rdf/accessControl/firsttime/allowed_entities_self_editor_edit_object_property.n3

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3987)**
[Vitro PR](https://github.com/vivo-project/Vitro/pull/468)
Added permissions required to upload main images.
* Reproduce the issue
* Test that users with following roles able to upload/remove images: Admin, Curator, Editor, Self editor
1. Access control

Added permissions required to upload images

---

api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/AddEditWebpageFormGenerator.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/edit/n3editing/configuration/generators/ManageWebpagesForIndividualGenerator.java
webapp/src/main/webapp/templates/freemarker/edit/forms/addEditWebpageForm.ftl

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3949)**: (please link to issue)
Fixes authorization checks on website forms by providing information about faux property
* Reproduce the problem in the issue
* Check that users with admin role are allowed to add and edit webpage faux object property with domain Person
* Try to add/create webpage as admin user
* Remove edit permission in faux object property configuration
* Try edit website, should not be authorized
* Remove add permission in faux object property configuration
* Try add website, should not be authorized

Fix for VIVO-3949

---

webapp/src/main/webapp/robots.txt

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [3935](https://github.com/vivo-project/VIVO/issues/3935)
[Linked Vitro PR](https://github.com/vivo-project/Vitro/pull/438)
Disallow access to /contact and /forgot-password to bots (at least to bots which respect robots.txt)
robots.txt is updated
Run VIVO and try to access to /contact and /forgotPassword from the web browser (this should work), and then testing robots.txt file by using some validator such as [this one](https://technicalseo.com/tools/robots-txt/). Please note that you run VIVO at some public address as a root application (meaning it should not be http://somedomain.com/vivo, it should be http://somedomain.com)

Disallow forms (with CAPTCHA) to bots

---

webapp/src/main/webapp/templates/freemarker/edit/forms/pageManagement--customDataScript.ftl

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3963)**
[Vitro PR](https://github.com/vivo-project/Vitro/pull/454)
Enables TinyMCE editor for Fixed HTML field.
- Create/Edit Fixed html pages, check result

Enable tinyMCE for fixed html pages

---

webapp/src/main/webapp/templates/freemarker/body/search/search-csvResults.ftl

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/4000)**
[Related Vitro PR](https://github.com/vivo-project/Vitro/pull/472)
Removes leading lines from template to export search results in csv format.
* Go to search page
* Export search results to CSV
* Verify that there are no longer not csv formatted lines at the beginning on the file
* Verify that filename contains date time and site name.
@VIVO-project/vivo-committers @hauschke 
1. FreeMarker
A reviewer should briefly …

VIVO-4000 Fixes for search result export to CSV

---

installer/home/pom.xml
installer/home/src/main/assembly/home.xml
installer/webapp/pom.xml

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3034)**
[Vitro PR](https://github.com/vivo-project/Vitro/pull/479)
Decoupled deployment and installation processes
Changed delivery of home directory: package it's contents as part of war artifact, update default files on home directory except rdf subdirectory on startup. 
In case tomcat directory is not provided artifact will not be copied into tomcat webapps directory
Changed deployment: war artifact is copied into webapp directory, not unpacked
Home directory contents are copied into war artifact
On startup path to home directory is being created if not already exists.
RDFFilesLoader and FileGraphSetup were adjusted to read rdf contents from tomcat webapp application directory
Test update of already installed instance …

Decouple installation and deployment

---

api/src/main/java/org/vivoweb/webapp/controller/freemarker/CreateAndLinkResourceController.java

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/4044)**
Fixes authorization request for claiming DOIs on related profiles
* Reproduce the issue
* Test that the pull request fixes the issue
1. Java

Fixed authorization request for claiming DOI on related profiles

---

api/src/main/java/org/vivoweb/webapp/startup/DataGetterN3Setup.java
home/src/main/resources/rdf/display/firsttime/search_individuals_vivo.n3
webapp/src/main/webapp/js/menupage/processDataGetterUtils.js
webapp/src/main/webapp/templates/freemarker/body/partials/shortview/view-browse-people.ftl
webapp/src/main/webapp/templates/freemarker/edit/forms/pageManagement--customDataScript.ftl
webapp/src/main/webapp/themes/nemo/templates/search.ftl
webapp/src/main/webapp/themes/nemo/templates/view-browse-default.ftl
webapp/src/main/webapp/themes/nemo/templates/view-browse-people.ftl
webapp/src/main/webapp/themes/tenderfoot/templates/page/partials/search.ftl
webapp/src/main/webapp/themes/wilma/templates/search.ftl

[Vitro PR](https://github.com/vivo-project/Vitro/pull/473)
Adds an option to select search filter to display filtered results on custom page.
Please take a look at Vitro PR first.
Updated PageManagement entry form files to align with Vitro PR.
* Create a new page in PageManagement menu. use type filter as an example
* Browse page, try selecting facets, alphabetical index, pagination
* Test the same in non i18n VIVO
This change require documentation to be updated.
@hauschke @VIVO-project/vivo-committers
1. Java
2. Freemarker
**Please update the following template which should be used by reviewers.**
A reviewer should provide here comments and suggestions for …

 Browse filter results on page

---

.github/workflows/deploy.yml
installer/pom.xml
pom.xml

**[4082](https://github.com/vivo-project/VIVO/issues/4082)**
[linked Vitro PR](https://github.com/vivo-project/Vitro/pull/499)
Fixing the issue with deploying VIVO/Vitro artefacts into the Maven central repository. It is done via Central Publisher Portal. So far it works over OSSRH which support will be discontinued (see [here](https://central.sonatype.org/publish/publish-maven/)). 
Sonatype plugin was replaced as well as configuration for publisher portal. 
Please follow the testing instructions in the linked [issue](https://github.com/vivo-project/VIVO/issues/4082)
**Please add any new expertise in the list which might be needed for reviewing your PR or remove any of the listed if it is not needed.** …

Migrating from OSSRH to Central Publisher Portal

---

api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/ExportQrCodeController.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/freemarker/InstitutionalInternalClassController.java
api/src/main/java/edu/cornell/mannlib/vitro/webapp/controller/visualization/ShortURLVisualizationController.java
api/src/main/java/org/vivoweb/webapp/sitemap/SiteMapServlet.java
home/src/main/resources/config/example.runtime.properties

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues/3846)**: (please link to issue)
[Vitro PR](https://github.com/vivo-project/Vitro/pull/475)
New boolean configuration property context.path.exclude to exclude tomcat application context from generated links useful in case the application is deployed with reverse proxy.
Created context.path.exclude configuration property to exclude context path from generated links. 
Replaced calls for context path to utility methods that allow overriding default context path.
Default behavior when configuration property is not set should be the same.
* To test application behind proxy one would need to configure webserver and tomcat in proxy mode like described in workaround of linked issue and set  context.path.exclude = true in …

Exclude context path from application generated links

---

.github/workflows/codeql-analysis.yml

**[VIVO GitHub issue](https://github.com/vivo-project/VIVO/issues)**: [4089](https://github.com/vivo-project/VIVO/issues/4089)
[The official instructions for upgrade](https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/)
This PR is upgrading codeql by following instructions available at this [link](https://github.blog/changelog/2025-01-10-code-scanning-codeql-action-v2-is-now-deprecated/#exactly-what-do-i-need-to-change)
Open PR Analyze log and check if there is any error in the Annotations section. 
For instance, compare PR error log before:
- https://github.com/vivo-project/VIVO/actions/runs/15633658215/job/44043533432?pr=4084 and 
- …

Upgrade codeql to version 3
